/******************************************************************************
 * This file is part of de.bb.tools.bnm.core.
 *
 *   de.bb.tools.bnm.core is free software: you can redistribute it and/or modify
 *   it under the terms of the GNU General Public License as published by
 *   the Free Software Foundation, either version 3 of the License, or
 *   (at your option) any later version.
 *
 *   de.bb.tools.bnm.core is distributed in the hope that it will be useful,
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *   GNU General Public License for more details.
 *
 *   You should have received a copy of the GNU General Public License
 *   along with de.bb.tools.bnm.core.  If not, see <http://www.gnu.org/licenses/>.
 *   
 *   (c) by Stefan "Bebbo" Franke 2009
 */

// generated by Xsd2Class
package de.bb.tools.bnm.model;

public class DeploymentRepository {
  /** 
   * Whether to assign snapshots a unique version comprised of the timestamp and build number, or to
   * use the same version each time
   */
  public boolean uniqueVersion;
  /** 
   * A unique identifier for a repository. This is used to match the repository to configuration in
   * the <code>settings.xml</code> file, for example.
   */
  public String id;
  /** 
   * Human readable name of the repository.
   */
  public String name;
  /** 
   * The url of the repository, in the form <code>protocol://hostname/path</code>.
   */
  public String url;
  /** 
   * The type of layout this repository uses for locating and storing artifacts - can be <code>legacy</code> or
   * <code>default</code>.
   */
  public String layout;
}
