/******************************************************************************
 * This file is part of de.bb.tools.bnm.core.
 *
 *   de.bb.tools.bnm.core is free software: you can redistribute it and/or modify
 *   it under the terms of the GNU General Public License as published by
 *   the Free Software Foundation, either version 3 of the License, or
 *   (at your option) any later version.
 *
 *   de.bb.tools.bnm.core is distributed in the hope that it will be useful,
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *   GNU General Public License for more details.
 *
 *   You should have received a copy of the GNU General Public License
 *   along with de.bb.tools.bnm.core.  If not, see <http://www.gnu.org/licenses/>.
 *   
 *   (c) by Stefan "Bebbo" Franke 2009
 */

// generated by Xsd2Class
package de.bb.tools.bnm.model;

import java.util.ArrayList;
import java.util.Map;

public class Developer {
  /** 
   * The unique ID of the developer in the SCM.
   */
  public String id;
  /** 
   * The full name of the contributor.
   */
  public String name;
  /** 
   * The email address of the contributor.
   */
  public String email;
  /** 
   * The URL for the homepage of the contributor.
   */
  public String url;
  /** 
   * The organization to which the contributor belongs.
   */
  public String organization;
  /** 
   * The URL of the organization.
   */
  public String organizationUrl;
  /** 
   * The roles the contributor plays in the project.  Each role is
   * described by a <code>role</code> element, the body of which is a
   * role name. This can also be used to describe the contribution.
   */
  public ArrayList<String> roles;
  /** 
   * The timezone the contributor is in. This is a number in the range -11 to 12.
   */
  public String timezone;
  /** 
   * Properties about the contributor, such as an instant messenger handle.
   */
  public Map<String, Object> properties;
}
