/******************************************************************************
 * This file is part of de.bb.tools.bnm.core.
 *
 *   de.bb.tools.bnm.core is free software: you can redistribute it and/or modify
 *   it under the terms of the GNU General Public License as published by
 *   the Free Software Foundation, either version 3 of the License, or
 *   (at your option) any later version.
 *
 *   de.bb.tools.bnm.core is distributed in the hope that it will be useful,
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *   GNU General Public License for more details.
 *
 *   You should have received a copy of the GNU General Public License
 *   along with de.bb.tools.bnm.core.  If not, see <http://www.gnu.org/licenses/>.
 *   
 *   (c) by Stefan "Bebbo" Franke 2009
 */

// generated by Xsd2Class
package de.bb.tools.bnm.model;

import de.bb.tools.bnm.model.DeploymentRepository;
import de.bb.tools.bnm.model.Relocation;
import de.bb.tools.bnm.model.Site;

public class DistributionManagement {
  /** 
   * Information needed to deploy the artifacts generated by the project to a remote repository.
   */
  public DeploymentRepository repository;
  /** 
   * Where to deploy snapshots of artifacts to. If not given, it defaults to the <code>repository</code> element.
   */
  public DeploymentRepository snapshotRepository;
  /** 
   * Information needed for deploying the web site of the project.
   */
  public Site site;
  /** 
   * The URL of the project?s download page. If not given users will be referred to the homepage given by
   * <code>url</code>. This is given to assist in locating artifacts that are not in the repository due to
   * licensing restrictions.
   */
  public String downloadUrl;
  /** 
   * Relocation information of the artifact if it has been moved to a new group ID and/or artifact ID.
   */
  public Relocation relocation;
  /** 
   * Gives the status of this artifact in the remote repository. This must not be set in your local
   * project, as it is updated by tools placing it in the reposiory. Valid values are: <code>none</code> (default),
   * <code>converted</code> (repository manager converted this from an Maven 1 POM), <code>partner</code>
   * (directly synced from a partner Maven 2 repository), <code>deployed</code> (was deployed from a Maven 2
   * instance), <code>verified</code> (has been hand verified as correct and final).
   */
  public String status;
}
