/******************************************************************************
 * This file is part of de.bb.tools.bnm.core.
 *
 *   de.bb.tools.bnm.core is free software: you can redistribute it and/or modify
 *   it under the terms of the GNU General Public License as published by
 *   the Free Software Foundation, either version 3 of the License, or
 *   (at your option) any later version.
 *
 *   de.bb.tools.bnm.core is distributed in the hope that it will be useful,
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *   GNU General Public License for more details.
 *
 *   You should have received a copy of the GNU General Public License
 *   along with de.bb.tools.bnm.core.  If not, see <http://www.gnu.org/licenses/>.
 *   
 *   (c) by Stefan "Bebbo" Franke 2009
 */

// generated by Xsd2Class
package de.bb.tools.bnm.model;

public class License {
  /** 
   * The full legal name of the license.
   */
  public String name;
  /** 
   * The official url for the license text.
   */
  public String url;
  /** 
   * The primary method by which this project may be distributed.
   * <dl>
   * <dt>repo</dt>
   * <dd>may be downloaded from the Maven repository</dd>
   * <dt>manual</dt>
   * <dd>user must manually download and install the dependency.</dd>
   * </dl>
   */
  public String distribution;
  /** 
   * Addendum information pertaining to this license.
   */
  public String comments;
}
