/******************************************************************************
 * This file is part of de.bb.tools.bnm.core.
 *
 *   de.bb.tools.bnm.core is free software: you can redistribute it and/or modify
 *   it under the terms of the GNU General Public License as published by
 *   the Free Software Foundation, either version 3 of the License, or
 *   (at your option) any later version.
 *
 *   de.bb.tools.bnm.core is distributed in the hope that it will be useful,
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *   GNU General Public License for more details.
 *
 *   You should have received a copy of the GNU General Public License
 *   along with de.bb.tools.bnm.core.  If not, see <http://www.gnu.org/licenses/>.
 *   
 *   (c) by Stefan "Bebbo" Franke 2009
 */

// generated by Xsd2Class
package de.bb.tools.bnm.model;

import java.util.ArrayList;

public class MailingList {
  /** 
   * The name of the mailing list.
   */
  public String name;
  /** 
   * The email address or link that can be used to subscribe to the mailing list.
   * If this is an email address, a
   * <code>mailto:</code> link will automatically be created when
   * the documentation is created.
   */
  public String subscribe;
  /** 
   * The email address or link that can be used to unsubscribe to
   * the mailing list.  If this is an email address, a
   * <code>mailto:</code> link will automatically be created
   * when the documentation is created.
   */
  public String unsubscribe;
  /** 
   * The email address or link that can be used to post to
   * the mailing list.  If this is an email address, a
   * <code>mailto:</code> link will automatically be created
   * when the documentation is created.
   */
  public String post;
  /** 
   * The link to a URL where you can browse the mailing list archive.
   */
  public String archive;
  /** 
   * The link to alternate URLs where you can browse the list archive.
   */
  public ArrayList<String> otherArchives;
}
