/******************************************************************************
 * This file is part of de.bb.tools.bnm.core.
 *
 *   de.bb.tools.bnm.core is free software: you can redistribute it and/or modify
 *   it under the terms of the GNU General Public License as published by
 *   the Free Software Foundation, either version 3 of the License, or
 *   (at your option) any later version.
 *
 *   de.bb.tools.bnm.core is distributed in the hope that it will be useful,
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *   GNU General Public License for more details.
 *
 *   You should have received a copy of the GNU General Public License
 *   along with de.bb.tools.bnm.core.  If not, see <http://www.gnu.org/licenses/>.
 *   
 *   (c) by Stefan "Bebbo" Franke 2009
 */

// generated by Xsd2Class
package de.bb.tools.bnm.model;

import java.util.ArrayList;

import de.bb.tools.bnm.Bind;

public class Resource {
    /**
     * Allows overriding of resources. Empty target path on overriding means
     * removal.
     */
    public String id;
    /**
     * Describe the resource target path. For example, if you want that resource
     * to appear in a specific package (<code>org.apache.maven.messages</code>),
     * you must specify this element with this value:
     * <code>org/apache/maven/messages</code>. This is not required if you
     * simply put the resources in that directory structure at the source,
     * however.
     */
    public String targetPath;
    /**
     * Whether resources are filtered to replace tokens with parameterised
     * values or not. The values are taken from the <code>properties</code>
     * element and from the properties in the files listed in the
     * <code>filters</code> element.
     */
    public boolean filtering;
    /**
     * Describe the directory where the resources are stored. The path is
     * relative to the POM.
     */
    public String directory;
    /**
     * A list of patterns to include, e.g. <code>**&#47;*.xml</code>.
     */
    public ArrayList<String> includes;
    /**
     * A list of patterns to exclude, e.g. <code>**&#47;*.xml</code>
     */
    public ArrayList<String> excludes;

    public String toString() {
        return "<resource>\r\n" + Bind.append(2, this).toString()
                + "</resource>";
    }
    
    public ArrayList<String> getExcludes() {
        ArrayList<String> r = new ArrayList<String>();
        r.addAll(excludes);
        r.add("**/CVS/**");
        r.add("**/.svn/**");
        return r;
    }
}
