/*
 * This file is initially generated by MEJB.
 * PLACE YOUR MODIFICATIONS HERE!
*/

package de.bb.web.board.mejb;

import java.rmi.RemoteException;
import java.util.Collection;

import de.bb.web.board.mejb.ArticleHome;
import de.bb.web.board.mejb.ArticleHomeBaseBean;

public class ArticleHomeBean extends ArticleHomeBaseBean implements de.bb.web.board.mejb.ArticleHome {
    public ArticleHomeBean() throws java.rmi.RemoteException {
        super();
    }
    

    public long getCountForBoard(String s)
        throws RemoteException
    {
        double d = queryDouble("SELECT COUNT(*) FROM Article, Topic WHERE Article.id_topic=Topic.id AND Topic.id_board=?", new Object[] {
            s
        });
        return (long)d;
    }

    public Article findLastByBoard(String s)
        throws RemoteException
    {
        Collection collection = queryCollection("SELECT DISTINCT Article.* FROM Article, Topic WHERE Article.id_topic=Topic.id AND Topic.id_board=? ORDER BY Article.modified DESC", new Object[] {
            s
        });
        if(collection.size() == 0)
            return null;
        else
            return (Article)collection.iterator().next();
    }

    public Article findLastByTopic(String s)
        throws RemoteException
    {
        Collection collection = queryCollection("SELECT DISTINCT Article.* FROM Article WHERE Article.id_topic=? ORDER BY Article.modified DESC", new Object[] {
            s
        });
        if(collection.size() == 0)
            return null;
        else
            return (Article)collection.iterator().next();
    }

    public long getCountForTopic(String s)
        throws RemoteException
    {
        double d = queryDouble("SELECT COUNT(*) FROM Article WHERE Article.id_topic=?", new Object[] {
            s
        });
        return (long)d;
    }

}
