/*
 * This file is initially generated by MEJB.
 * PLACE YOUR MODIFICATIONS HERE!
*/

package de.bb.web.board.mejb;

import java.rmi.RemoteException;

import de.bb.web.board.mejb.ArticleHomeBase;

public interface ArticleHome extends ArticleHomeBase {

    public abstract long getCountForBoard(String s) throws RemoteException;

    public abstract Article findLastByBoard(String s) throws RemoteException;

    public abstract Article findLastByTopic(String s) throws RemoteException;

    public abstract long getCountForTopic(String s) throws RemoteException;
}
