/*
 * This file is initially generated by MEJB.
 * PLACE YOUR MODIFICATIONS HERE!
*/


package de.bb.web.board.mejb;

import de.bb.web.board.mejb.ArticleBase;

public interface Article extends ArticleBase
{
}
