/*
 * This file is generated by MEJB.
 * DO NOT MODIFY THIS FILE!
*/


package de.bb.web.board.mejb;

public interface ArticleBase extends de.bb.mejb.Simple
{
  public String getId() throws java.rmi.RemoteException;
  public String getTopicId() throws java.rmi.RemoteException;
  public Topic getTopic() throws java.rmi.RemoteException;
  public void setTopic(Topic a$Topic) throws java.rmi.RemoteException;
  public java.lang.String getAuthor() throws java.rmi.RemoteException;
  public void setAuthor(java.lang.String a$Author) throws java.rmi.RemoteException;
  public String getContent() throws java.rmi.RemoteException;
  public void setContent(String a$Content) throws java.rmi.RemoteException;
  public java.sql.Timestamp getModified() throws java.rmi.RemoteException;
  public void setModified(java.sql.Timestamp a$Modified) throws java.rmi.RemoteException;
  public StringBuffer toLog() throws java.rmi.RemoteException;
  public void store() throws java.rmi.RemoteException;
}
