/*
 * This file is generated by MEJB.
 * DO NOT MODIFY THIS FILE!
*/


package de.bb.web.board.mejb;

public interface ArticleHomeBase extends java.rmi.Remote, javax.ejb.EJBHome
{
  public Article findByPrimaryKey(Object pk) throws java.rmi.RemoteException;
  public Article create() throws java.rmi.RemoteException;
  public java.util.Collection findAll() throws java.rmi.RemoteException;
  public java.util.Collection findByTopic(Object id) throws java.rmi.RemoteException;
}
