/*
 * This file is initially generated by MEJB.
 * PLACE YOUR MODIFICATIONS HERE!
*/


package de.bb.web.board.mejb;

import de.bb.web.board.mejb.Article;
import de.bb.web.board.mejb.ArticleBaseBean;
import de.bb.web.board.mejb.ArticleHomeBaseBean;

public class ArticleBean
  extends ArticleBaseBean
  implements Article
{
  public ArticleBean(ArticleHomeBaseBean aHome) throws java.rmi.RemoteException
  {
    super(aHome);
  }
}
