/*
 * This file is generated by MEJB.
 * DO NOT MODIFY THIS FILE!
*/


package de.bb.web.board.mejb;

public interface BoardHomeBase extends java.rmi.Remote, javax.ejb.EJBHome
{
  public Board findByPrimaryKey(Object pk) throws java.rmi.RemoteException;
  public Board create() throws java.rmi.RemoteException;
  public java.util.Collection findAll() throws java.rmi.RemoteException;
}
