/*
 * This file is initially generated by MEJB.
 * PLACE YOUR MODIFICATIONS HERE!
*/


package de.bb.web.board.mejb;

import java.rmi.RemoteException;
import java.util.Collection;

import de.bb.web.board.mejb.Board;
import de.bb.web.board.mejb.BoardBaseBean;
import de.bb.web.board.mejb.BoardHomeBaseBean;

public class BoardBean
  extends BoardBaseBean
  implements Board
{
  public BoardBean(BoardHomeBaseBean aHome) throws java.rmi.RemoteException
  {
    super(aHome);
  }
  
  public String getMinReadPermission()
          throws RemoteException
      {
          StringBuffer stringbuffer = new StringBuffer();
          String s = getReadPermission();
          String s1 = getWritePermission();
          String s2 = getAdminPermission();
          if(s != null)
              stringbuffer.append(s);
          if(s1 != null && s1.length() > 0)
          {
              stringbuffer.append(';');
              stringbuffer.append(s1);
          }
          if(s2 != null && s2.length() > 0)
          {
              stringbuffer.append(';');
              stringbuffer.append(s2);
          }
          return stringbuffer.toString();
      }

      public String getMinWritePermission()
          throws RemoteException
      {
          StringBuffer stringbuffer = new StringBuffer();
          String s = getWritePermission();
          String s1 = getAdminPermission();
          if(s != null)
              stringbuffer.append(s);
          if(s1 != null && s1.length() > 0)
          {
              stringbuffer.append(';');
              stringbuffer.append(s1);
          }
          return stringbuffer.toString();
      }

      public Topic getLastTopic()
          throws RemoteException
      {
          TopicHomeBean topichomebean = new TopicHomeBean();
          return topichomebean.findLastByBoard(getId());
      }

      public long getTopicCount()
          throws RemoteException
      {
          TopicHomeBean topichomebean = new TopicHomeBean();
          return topichomebean.getCountForBoard(getId());
      }

      public long getArticleCount()
          throws RemoteException
      {
          ArticleHomeBean articlehomebean = new ArticleHomeBean();
          return articlehomebean.getCountForBoard(getId());
      }

      public Collection getSortedTopicList()
          throws RemoteException
      {
          TopicHomeBean topichomebean = new TopicHomeBean();
          return topichomebean.getSortedTopicList(getId());
      }
}
