/*
 * This file is initially generated by MEJB.
 * PLACE YOUR MODIFICATIONS HERE!
*/


package de.bb.web.board.mejb;

import java.rmi.RemoteException;
import java.util.Collection;

import de.bb.web.board.mejb.BoardHomeBase;

public interface BoardHome extends BoardHomeBase
{

    Collection findAllOrdered() throws RemoteException;
}
