/*
 * This file is generated by MEJB.
 * DO NOT MODIFY THIS FILE!
*/


package de.bb.web.board.mejb;

public interface BoardBase extends de.bb.mejb.Simple
{
  public String getId() throws java.rmi.RemoteException;
  public java.lang.String getReadPermission() throws java.rmi.RemoteException;
  public void setReadPermission(java.lang.String a$ReadPermission) throws java.rmi.RemoteException;
  public java.lang.String getWritePermission() throws java.rmi.RemoteException;
  public void setWritePermission(java.lang.String a$WritePermission) throws java.rmi.RemoteException;
  public java.lang.String getAdminPermission() throws java.rmi.RemoteException;
  public void setAdminPermission(java.lang.String a$AdminPermission) throws java.rmi.RemoteException;
  public java.lang.String getName() throws java.rmi.RemoteException;
  public void setName(java.lang.String a$Name) throws java.rmi.RemoteException;
  public java.lang.String getDescription() throws java.rmi.RemoteException;
  public void setDescription(java.lang.String a$Description) throws java.rmi.RemoteException;
  public int getGroupNr() throws java.rmi.RemoteException;
  public void setGroupNr(int a$GroupNr) throws java.rmi.RemoteException;
  public int getOrderNr() throws java.rmi.RemoteException;
  public void setOrderNr(int a$OrderNr) throws java.rmi.RemoteException;
  public StringBuffer toLog() throws java.rmi.RemoteException;
  public void store() throws java.rmi.RemoteException;
  public java.util.Collection getTopicList() throws java.rmi.RemoteException;
}
