/*
 * This file is initially generated by MEJB.
 * PLACE YOUR MODIFICATIONS HERE!
*/


package de.bb.web.board.mejb;

import java.rmi.RemoteException;
import java.util.Collection;

import de.bb.web.board.mejb.BoardBase;

public interface Board extends BoardBase
{

    public abstract String getMinReadPermission()
        throws RemoteException;

    public abstract String getMinWritePermission()
        throws RemoteException;

    public abstract Topic getLastTopic()
        throws RemoteException;

    public abstract long getTopicCount()
        throws RemoteException;

    public abstract long getArticleCount()
        throws RemoteException;

    public abstract Collection getSortedTopicList()
        throws RemoteException;
}
