/*
 * This file is generated by MEJB.
 * DO NOT MODIFY THIS FILE!
*/


package de.bb.web.board.mejb;

public class Finder extends de.bb.mejb.Finder
{
  public Finder(java.util.Properties properties) throws javax.naming.NamingException
  {
    super(properties);
  }
  /** return the home object.
   * @throws java.rmi.RemoteException
   * @return the home object */
  public BoardHome getBoardHome() throws java.rmi.RemoteException
  {
    try {
      return (BoardHome)getHome("de.bb.web.board.mejb.BoardHome");
    } catch (Exception ex) {
      throw new java.rmi.RemoteException(ex.getMessage());
    }
  }
  /** return the home object.
   * @throws java.rmi.RemoteException
   * @return the home object */
  public TopicHome getTopicHome() throws java.rmi.RemoteException
  {
    try {
      return (TopicHome)getHome("de.bb.web.board.mejb.TopicHome");
    } catch (Exception ex) {
      throw new java.rmi.RemoteException(ex.getMessage());
    }
  }
  /** return the home object.
   * @throws java.rmi.RemoteException
   * @return the home object */
  public ArticleHome getArticleHome() throws java.rmi.RemoteException
  {
    try {
      return (ArticleHome)getHome("de.bb.web.board.mejb.ArticleHome");
    } catch (Exception ex) {
      throw new java.rmi.RemoteException(ex.getMessage());
    }
  }
}
