/*
 * This file is initially generated by MEJB.
 * PLACE YOUR MODIFICATIONS HERE!
*/

package de.bb.web.board.mejb;

import java.rmi.RemoteException;

public class TopicBean extends TopicBaseBean implements Topic {
    public TopicBean(TopicHomeBaseBean aHome) throws java.rmi.RemoteException {
        super(aHome);
    }

    public long getArticleCount() throws RemoteException {
        ArticleHomeBean articlehomebean = new ArticleHomeBean();
        return articlehomebean.getCountForTopic(getId());
    }

    public Article getLastArticle() throws RemoteException {
        ArticleHomeBean articlehomebean = new ArticleHomeBean();
        return articlehomebean.findLastByTopic(getId());
    }
}
