/*
 * This file is generated by MEJB.
 * DO NOT MODIFY THIS FILE!
*/


package de.bb.web.board.mejb;

public interface TopicHomeBase extends java.rmi.Remote, javax.ejb.EJBHome
{
  public Topic findByPrimaryKey(Object pk) throws java.rmi.RemoteException;
  public Topic create() throws java.rmi.RemoteException;
  public java.util.Collection findAll() throws java.rmi.RemoteException;
  public java.util.Collection findByBoard(Object id) throws java.rmi.RemoteException;
}
