/*
 * This file is initially generated by MEJB.
 * PLACE YOUR MODIFICATIONS HERE!
*/

package de.bb.web.board.mejb;

import java.rmi.RemoteException;
import java.util.Collection;

public interface TopicHome extends TopicHomeBase {
    public abstract long getCountForBoard(String s) throws RemoteException;

    public abstract Collection getSortedTopicList(String s) throws RemoteException;

    public abstract Topic findLastByBoard(String s) throws RemoteException;

    public abstract Collection findRecent(long l) throws RemoteException;

    public abstract Collection findRecent(long l, String s) throws RemoteException;
}
