/*
 * This file is initially generated by MEJB.
 * PLACE YOUR MODIFICATIONS HERE!
*/


package de.bb.web.user.mejb;

import java.rmi.RemoteException;
import java.util.Collection;

public interface PermissionHome extends PermissionHomeBase
{

    Permission findByName(String string) throws RemoteException;

    Collection<Permission> findByPerson(Person p) throws RemoteException;
}
