/*
 * This file is generated by MEJB.
 * DO NOT MODIFY THIS FILE!
*/


package de.bb.web.user.mejb;

public interface PermissionHomeBase extends java.rmi.Remote, javax.ejb.EJBHome
{
  public Permission findByPrimaryKey(Object pk) throws java.rmi.RemoteException;
  public Permission create() throws java.rmi.RemoteException;
  public java.util.Collection findAll() throws java.rmi.RemoteException;
}
