/*
 * This file is generated by MEJB.
 * DO NOT MODIFY THIS FILE!
*/


package de.bb.web.user.mejb;

abstract class PermissionHomeBaseBean
  extends de.bb.mejb.CMPHomeBean
  implements de.bb.web.user.mejb.PermissionHomeBase
{
  private static de.bb.mejb.CMPDbi dbi = null;
  protected de.bb.mejb.CMPDbi getDbi() { return dbi; }
  private synchronized void init() throws java.rmi.RemoteException
  {
    dbi = initDbi("de.bb.web.user.mejb", "Permission");
  }

  PermissionHomeBaseBean() throws java.rmi.RemoteException
  {
    super("Permission");
    if (dbi == null)
      init();
  }
  public javax.ejb.EJBMetaData getEJBMetaData() throws java.rmi.RemoteException
  {
    return null;
  }
  public javax.ejb.HomeHandle getHomeHandle() throws java.rmi.RemoteException
  {
    return null;
  }
  public void remove(Object o) throws java.rmi.RemoteException
  {
    remove((de.bb.mejb.CMPBean)o, dbi);
  }
  public void remove(javax.ejb.Handle handle) throws java.rmi.RemoteException
  {
  }
  public de.bb.web.user.mejb.Permission findByPrimaryKey(Object pk) throws java.rmi.RemoteException
  {
    return (de.bb.web.user.mejb.Permission)readByPrimaryKey(pk, dbi);
  }
  public de.bb.web.user.mejb.Permission create() throws java.rmi.RemoteException
  {
    return new PermissionBean(this);
  }
  // not ejb standard functions
  public de.bb.mejb.Simple internCreate() throws java.rmi.RemoteException
  {
    return (de.bb.mejb.Simple)create();
  }
  void store(Object o) throws java.rmi.RemoteException
  {
    store((de.bb.mejb.CMPBean)o, 2, dbi);
  }
  PermissionBean load(Object obj) throws java.rmi.RemoteException
  {
    PermissionBean o = (PermissionBean) obj;
    load(o, dbi);
    return o;
  }
  public java.util.Collection findAll() throws java.rmi.RemoteException
  {
    return this.queryCollection("SELECT * FROM Permission ORDER BY ID", NOPARAM);
  }
}
