/*
 * This file is initially generated by MEJB.
 * PLACE YOUR MODIFICATIONS HERE!
*/

package de.bb.web.user.mejb;

import java.rmi.RemoteException;
import java.util.Collection;

public class Person2PermissionHomeBean extends Person2PermissionHomeBaseBean implements
        de.bb.web.user.mejb.Person2PermissionHome {
    public Person2PermissionHomeBean() throws java.rmi.RemoteException {
        super();
    }

    public Person2Permission findByPersonPermission(Person p, Permission perm) throws RemoteException {
        Collection<Person2Permission> c = this.queryCollection(
                "SELECT * FROM Permission2Permission WHERE id_person = ? AND id_permission = ?",
                new Object[] { p.getId(), perm.getId() });
        if (c.isEmpty())
            return null;
        return c.iterator().next();
    }
}
