/*
 * This file is initially generated by MEJB.
 * PLACE YOUR MODIFICATIONS HERE!
*/


package de.bb.web.user.mejb;

public class PersonBean
  extends PersonBaseBean
  implements Person
{
  public PersonBean(PersonHomeBaseBean aHome) throws java.rmi.RemoteException
  {
    super(aHome);
  }
}
