/*
 * This file is initially generated by MEJB.
 * PLACE YOUR MODIFICATIONS HERE!
*/


package de.bb.web.user.mejb;

public class Person2PermissionBean
  extends Person2PermissionBaseBean
  implements de.bb.web.user.mejb.Person2Permission
{
  public Person2PermissionBean(Person2PermissionHomeBaseBean aHome) throws java.rmi.RemoteException
  {
    super(aHome);
  }
}
