/******************************************************************************
 * This file is part of de.bb.tools.bnm.core.
 *
 *   de.bb.tools.bnm.core is free software: you can redistribute it and/or modify
 *   it under the terms of the GNU General Public License as published by
 *   the Free Software Foundation, either version 3 of the License, or
 *   (at your option) any later version.
 *
 *   de.bb.tools.bnm.core is distributed in the hope that it will be useful,
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *   GNU General Public License for more details.
 *
 *   You should have received a copy of the GNU General Public License
 *   along with de.bb.tools.bnm.core.  If not, see <http://www.gnu.org/licenses/>.
 *   
 *   (c) by Stefan "Bebbo" Franke 2009
 */

// generated by Xsd2Class
package de.bb.tools.bnm.setting;

import java.util.Map;

public class Server {
  /**
   * The username used to authenticate.
   */
  public String username;
  /**
   * The password used in conjunction with the username to authenticate.
   */
  public String password;
  /**
   * The private key location used to authenticate.
   */
  public String privateKey;
  /**
   * The passphrase used in conjunction with the privateKey to authenticate.
   */
  public String passphrase;
  /**
   * The permissions for files when they are created.
   */
  public String filePermissions;
  /**
   * The permissions for directories when they are created.
   */
  public String directoryPermissions;
  /**
   * Extra configuration for the transport layer.
   */
  public Map<String,String> configuration;
  public String id;
}
