/******************************************************************************
 * This file is part of de.bb.tools.bnm.core.
 *
 *   de.bb.tools.bnm.core is free software: you can redistribute it and/or modify
 *   it under the terms of the GNU General Public License as published by
 *   the Free Software Foundation, either version 3 of the License, or
 *   (at your option) any later version.
 *
 *   de.bb.tools.bnm.core is distributed in the hope that it will be useful,
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *   GNU General Public License for more details.
 *
 *   You should have received a copy of the GNU General Public License
 *   along with de.bb.tools.bnm.core.  If not, see <http://www.gnu.org/licenses/>.
 *   
 *   (c) by Stefan "Bebbo" Franke 2009
 */

// generated by Xsd2Class
package de.bb.tools.bnm.setting;

import java.util.ArrayList;

public class Settings {
  /**
   * The local repository.
   */
  public String localRepository;
  /**
   * Whether Maven should attempt to interact with the user for input.
   */
  public boolean interactiveMode;
  /**
   * Whether Maven should use the plugin-registry.xml file to manage plugin versions.
   */
  public boolean usePluginRegistry;
  /**
   * Indicate whether maven should operate in offline mode full-time.
   */
  public boolean offline;
  /**
   * Configuration for different proxy profiles. Multiple proxy profiles
   * might come in handy for anyone working from a notebook or other
   * mobile platform, to enable easy switching of entire proxy
   * configurations by simply specifying the profile id, again either from
   * the command line or from the defaults section below.
   */
  public ArrayList<Proxy> proxies;
  /**
   * Configuration of server-specific settings, mainly authentication
   * method. This allows configuration of authentication on a per-server
   * basis.
   */
  public ArrayList<Server> servers;
  /**
   * Configuration of download mirrors for repositories.
   */
  public ArrayList<Mirror> mirrors;
  /**
   * Configuration of build profiles for adjusting the build
   * according to environmental parameters.
   */
  public ArrayList<Profile> profiles;
  /**
   * List of manually-activated build profiles, specified in the order in which
   * they should be applied.
   */
  public ArrayList<String> activeProfiles;
  /**
   * List of groupIds to search for a plugin when that plugin
   * groupId is not explicitly provided.
   */
  public ArrayList<String> pluginGroups;
}
