/*
 * This file is initially generated by MEJB.
 * PLACE YOUR MODIFICATIONS HERE!
*/


package de.bb.web.user.mejb;

/**
 * @author sfranke
 */
public interface Permission extends PermissionBase
{
}
