/*
 * This file is initially generated by MEJB.
 * PLACE YOUR MODIFICATIONS HERE!
*/


package de.bb.web.user.mejb;

public class PermissionBean
  extends PermissionBaseBean
  implements Permission
{
  public PermissionBean(PermissionHomeBaseBean aHome) throws java.rmi.RemoteException
  {
    super(aHome);
  }
}
