/*
 * This file is initially generated by MEJB.
 * PLACE YOUR MODIFICATIONS HERE!
 */

package de.bb.web.user.mejb;

import java.rmi.RemoteException;
import java.util.Collection;

import javax.ejb.EJBHome;

import de.bb.mejb.Simple;

public class PermissionHomeBean extends PermissionHomeBaseBean implements
    PermissionHome
{
  public PermissionHomeBean(EJBHome home) throws java.rmi.RemoteException
  {
    super(home);
  }

  /* (non-Javadoc)
   * @see jspboard.ejb.PermissionHome#findByPerson(jspboard.ejb.Person)
   */
  public Collection findByPerson(Person p) throws RemoteException
  {
    return queryCollection(
        "SELECT Permission.* from Permission, Person2Permission "
            + "WHERE Person2Permission.id_person=? "
            + "AND Person2Permission.id_permission=Permission.id",
        new Object[] { p.getId() });
  }

  /* (non-Javadoc)
   * @see jspboard.ejb.PermissionHome#findByName(java.lang.String)
   */
  public Permission findByName(String permission) throws RemoteException
  {
    Collection c = queryCollection("SELECT Permission.* from Permission "
        + "WHERE name=? ", new Object[] { permission });
    if (c.size() != 1)
      return null;
    return (Permission) c.iterator().next();
  }

  public Simple internCreate() throws RemoteException {
    return new PermissionBean(this);
  }
  
}