/*
 * This file is generated by MEJB.
 * DO NOT MODIFY THIS FILE!
*/


package de.bb.web.user.mejb;

public interface PermissionBase extends de.bb.mejb.Simple
{
  public String getId() throws java.rmi.RemoteException;
  public java.lang.String getName() throws java.rmi.RemoteException;
  public void setName(java.lang.String a$Name) throws java.rmi.RemoteException;
  public StringBuffer toLog() throws java.rmi.RemoteException;
  public void store() throws java.rmi.RemoteException;
  public java.util.Collection getPerson2PermissionList() throws java.rmi.RemoteException;
}
