/*
 * This file is initially generated by MEJB.
 * PLACE YOUR MODIFICATIONS HERE!
*/


package de.bb.web.user.mejb;

import java.rmi.RemoteException;
import java.util.Collection;

public interface PermissionHome extends PermissionHomeBase
{

  /**
   * @param p
   * @return
   */
  Collection findByPerson(Person p) throws RemoteException;

  /**
   * @param permission
   * @return
   */
  Permission findByName(String permission) throws RemoteException;
}
