/*
 * This file is initially generated by MEJB.
 * PLACE YOUR MODIFICATIONS HERE!
*/


package de.bb.web.user.mejb;

import java.rmi.RemoteException;

public interface Person2PermissionHome extends Person2PermissionHomeBase
{

  /**
   * @param p
   * @param perm
   * @return
   */
  Person2Permission findByPersonPermission(Person p, Permission perm) throws RemoteException;
}
