/*
 * This file is generated by MEJB.
 * DO NOT MODIFY THIS FILE!
*/


package de.bb.web.user.mejb;

public interface PersonBase extends de.bb.mejb.Simple
{
  public String getId() throws java.rmi.RemoteException;
  public java.lang.String getName() throws java.rmi.RemoteException;
  public void setName(java.lang.String a$Name) throws java.rmi.RemoteException;
  public java.lang.String getEmail() throws java.rmi.RemoteException;
  public void setEmail(java.lang.String a$Email) throws java.rmi.RemoteException;
  public java.lang.String getPassword() throws java.rmi.RemoteException;
  public void setPassword(java.lang.String a$Password) throws java.rmi.RemoteException;
  public java.sql.Timestamp getLastVisit() throws java.rmi.RemoteException;
  public void setLastVisit(java.sql.Timestamp a$LastVisit) throws java.rmi.RemoteException;
  public int getPostCount() throws java.rmi.RemoteException;
  public void setPostCount(int a$PostCount) throws java.rmi.RemoteException;
  public java.lang.String getAvatar() throws java.rmi.RemoteException;
  public void setAvatar(java.lang.String a$Avatar) throws java.rmi.RemoteException;
  public java.lang.String getPrename() throws java.rmi.RemoteException;
  public void setPrename(java.lang.String a$Prename) throws java.rmi.RemoteException;
  public java.lang.String getSurname() throws java.rmi.RemoteException;
  public void setSurname(java.lang.String a$Surname) throws java.rmi.RemoteException;
  public java.lang.String getStreet() throws java.rmi.RemoteException;
  public void setStreet(java.lang.String a$Street) throws java.rmi.RemoteException;
  public java.lang.String getCity() throws java.rmi.RemoteException;
  public void setCity(java.lang.String a$City) throws java.rmi.RemoteException;
  public java.lang.String getPlz() throws java.rmi.RemoteException;
  public void setPlz(java.lang.String a$Plz) throws java.rmi.RemoteException;
  public java.lang.String getPhone1() throws java.rmi.RemoteException;
  public void setPhone1(java.lang.String a$Phone1) throws java.rmi.RemoteException;
  public java.lang.String getPhone2() throws java.rmi.RemoteException;
  public void setPhone2(java.lang.String a$Phone2) throws java.rmi.RemoteException;
  public StringBuffer toLog() throws java.rmi.RemoteException;
  public void store() throws java.rmi.RemoteException;
  public java.util.Collection getPerson2PermissionList() throws java.rmi.RemoteException;
}
