/*
 * This file is initially generated by MEJB.
 * PLACE YOUR MODIFICATIONS HERE!
 */

package de.bb.web.user.mejb;

import java.rmi.RemoteException;
import java.util.Collection;

import javax.ejb.EJBHome;

import de.bb.mejb.Simple;

public class Person2PermissionHomeBean extends Person2PermissionHomeBaseBean
    implements Person2PermissionHome
{
  public Person2PermissionHomeBean(EJBHome home)
      throws java.rmi.RemoteException
  {
    super(home);
  }

  /* (non-Javadoc)
   * @see jspboard.ejb.Person2PermissionHome#findByPersonPermission(jspboard.ejb.Person, jspboard.ejb.Permission)
   */
  public Person2Permission findByPersonPermission(Person p, Permission perm)
      throws RemoteException
  {
    Collection c = queryCollection("SELECT * FROM Person2Permission WHERE "
        + "id_person=? AND id_permission=?", new Object[] { p.getId(),
        perm.getId() });
    if (c.size() != 1)
      return null;
    return (Person2Permission) c.iterator().next();
  }

  public Simple internCreate() throws RemoteException {
    return new Person2PermissionBean(this);
  }
}