package de.bb.sql;
/**
 * Defines a method to handle log messages generated by de.bb.sql.
 * Use the Method Connection.setLogger to replace the default Logger instance.
 * 
 * @author sfranke
 */
public interface Logger {
  /**
   * This hook is called with an error message.
   * The implementation can handle this message in application default behaviour. 
   */
  public void logError(String message);
}
